### ISSUE TITLE
OrdersUsingCommonTypeConversion test fails

### ISSUE THREAD

**Issue by patriksvensson** [statiqdev/Statiq.Framework#111]
I suspect this has something to do with non-culture neutral comparisons since my computer is set to Swedish region, and we use a sane date format over here 😉 

```
A total of 1 test files matched the specified pattern.
  X OrdersUsingCommonTypeConversion [46ms]
  Error Message:
   Shouldly.ShouldAssertException : results
    should be
[[["Foo" => 2009-01-01T00:00:00.0000000], ["Source" => ], ["Destination" => ], ["ContentProvider" => Statiq.Common.NullContent (18021239)]], [["Foo" => "1/1/2010"], ["Source" => ], ["Destination" => ], ["ContentProvider" => Statiq.Common.NullContent (40482101)]]]
    but was
[[["Foo" => "1/1/2010"], ["Source" => ], ["Destination" => ], ["ContentProvider" => Statiq.Common.NullContent (40482101)]], [["Foo" => 2009-01-01T00:00:00.0000000], ["Source" => ], ["Destination" => ], ["ContentProvider" => Statiq.Common.NullContent (18021239)]]]
    difference
[*[["Foo" => "1/1/2010"], ["Source" => ], ["Destination" => ], ["ContentProvider" => Statiq.Common.NullContent (40482101)]]*, *[["Foo" => 2009-01-01T00:00:00.0000000], ["Source" => ], ["Destination" => ], ["ContentProvider" => Statiq.Common.NullContent (18021239)]]*]
  Stack Trace:
     at Statiq.Core.Tests.Modules.Control.OrderDocumentsFixture.ExecuteTests.OrdersUsingCommonTypeConversion() in D:\Source\github\patriksvensson\statiq.framework\tests\core\Statiq.Core.Tests\Modules\Control\OrderDocumentsFixture.cs:line 297
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```

**Comment by daveaglick** [comment]
Is that the only test that fails for you? If so I'm impressed since I've given zero thought to testing alternate cultures so far (not that it's not important, just haven't dedicated time to it yet).
