### ISSUE TITLE
ValidateLinks fails with Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by darrelmiller** [statiqdev/Statiq.Framework#119]
I am running into in issue while trying to migrate an existing blog over.  I need to pull the source to try and pin down what input is causing this issue, but I figured I'd post the trace just in case it is obvious.  
```
[DBUG] LinkValidation/Output » ValidateLinks » Starting module execution... (266 input document(s))
[ERRO] Error while executing module ValidateLinks in LinkValidation/Output: Object reference not set to an instance of an object.
[DBUG] Exception while executing pipeline LinkValidation/Output: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Statiq.Html.ValidateLinks.<>c__DisplayClass7_0.<<ExecuteContextAsync>b__2>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at Statiq.Html.ValidateLinks.ExecuteContextAsync(IExecutionContext context)
   at Statiq.Common.Module.ExecuteAsync(IExecutionContext context)
   at Statiq.Common.Module.ExecuteAsync(IExecutionContext context)
   at Statiq.Core.Engine.ExecuteModulesAsync(ExecutionContextData contextData, IExecutionContext parent, IEnumerable`1 modules, ImmutableArray`1 inputs, ILogger logger)
```

**Comment by daveaglick** [comment]
I think I have an idea what's going on, looks like I don't properly stop processing after certain error conditions. Going to verify and try to squeeze a fix into the release I'm publishing tonight.

**Comment by daveaglick** [comment]
Yep, think I got it (or I just fixed a totally unrelated bug 🤣). Release will go out in a few hours.

**Comment by darrelmiller** [comment]
Awesome, thank you.  I think the URL that was causing an issue had some kind of placeholder {token} in it.  Not sure if that was what was causing the error.

**Comment by darrelmiller** [comment]
This fix solved my problem.  Thanks!
