### ISSUE TITLE
Error previewing CleanBlog using Statiq.Web beta.28

### ISSUE THREAD

**Issue by henrikrxn** [statiqdev/Statiq.Framework#188]
Been experimenting with Statiq.Web over the weekend and I created a repository for repo that contains the code resulting from following the steps in the Statiq.Web "Quick Start" and then adding CleanBlog theme as git submodule

https://github.com/henrikrxn/StatiqWebQuickStartWithCleanBlogTheme

**I tried downgrading Statiq.Web to beta.27 and everything works without any issues.**

Also tried adding a couple of posts, but that makes no difference.

`dotnet --info` is at the end. Using latest .NET 5 SDK

From a Powershell 7.1.3 command prompt:

`dotnet run -- preview -l Debug --clean-mode Full`

on the repository mentioned above I get (partial output)

```
[DBUG] Content/PostProcess » RenderContentPostProcessTemplates » ExecuteIf » ExecuteIf » ExecuteIf » ExecuteConfig » RenderRazor » Compiling /_layout.cshtml
[ERRO] Content/PostProcess » RenderContentPostProcessTemplates » ExecuteIf » ExecuteIf » ExecuteIf » ExecuteConfig » RenderRazor » [E:/Experiments/StatiqWebQuickStartWithCleanBlogTheme/StatiqWebQuickStartWithCleanBlogTheme/input/index.md => index.html] One or more compilation failures occurred:

[ERRO] Content/PostProcess » RenderContentPostProcessTemplates » ExecuteIf » ExecuteIf » ExecuteIf » ExecuteConfig » RenderRazor » [E:/Experiments/StatiqWebQuickStartWithCleanBlogTheme/StatiqWebQuickStartWithCleanBlogTheme/input/no-posts/first-post.md => no-posts/first-post.html] One or more compilation failures occurred:

[ERRO] Content/PostProcess » RenderContentPostProcessTemplates » ExecuteIf » ExecuteIf » ExecuteIf » ExecuteConfig » RenderRazor » [E:/Experiments/StatiqWebQuickStartWithCleanBlogTheme/StatiqWebQuickStartWithCleanBlogTheme/input/no-posts/second-post.md => no-posts/second-post.html] One or more compilation failures occurred:

[DBUG] Exception while executing pipeline Content/PostProcess: Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.CompilationFailedException: One or more compilation failures occurred:

   at Statiq.Razor.StatiqViewCompiler.CompileAndEmit(RazorCodeDocument codeDocument, String generatedCode)
   at Statiq.Razor.StatiqViewCompiler.<>c__DisplayClass17_0.<CompileAsync>b__0(CompilerCacheKey _)
   at Statiq.Common.ConcurrentCache`2.<>c__DisplayClass2_1.<GetOrAdd>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Statiq.Common.ConcurrentCache`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Statiq.Razor.CachingCompiler.GetOrAddCachedCompilation(CompilerCacheKey cacheKey, Func`2 valueFactory)
   at Statiq.Razor.StatiqViewCompiler.CompileAsync(String relativePath)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Statiq.Common.ConcurrentCache`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Lazy`1.get_Value()
   at Statiq.Razor.CachingCompiler.GetOrAddCachedCompilation(CompilerCacheKey cacheKey, Func`2 valueFactory)
   at Statiq.Razor.StatiqViewCompiler.CompileAsync(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromPath(String executingFilePath, String pagePath, Boolean isMainPage)
   at Statiq.Razor.StatiqViewCompiler.CompileAsync(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.GetPage(String executingFilePath, String pagePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.GetLayoutPage(ViewContext context, String executingFilePath, String layoutPath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromPath(String executingFilePath, String pagePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.GetLayoutPage(ViewContext context, String executingFilePath, String layoutPath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Statiq.Razor.RazorCompiler.RenderPageAsync(RenderRequest request)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Statiq.Razor.RazorCompiler.RenderPageAsync(RenderRequest request)
   at Statiq.Razor.RazorCompiler.RenderPageAsync(RenderRequest request)
   at Statiq.Razor.RazorService.RenderAsync(RenderRequest request)
   at Statiq.Razor.RazorService.RenderAsync(RenderRequest request)
   at Statiq.Razor.RazorService.RenderAsync(RenderRequest request)
   at Statiq.Razor.RenderRazor.<>c__DisplayClass16_0.<<ExecuteContextAsync>g__RenderDocumentAsync|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Statiq.Razor.RenderRazor.<>c__DisplayClass16_0.<<ExecuteContextAsync>g__RenderDocumentAsync|1>d.MoveNext()
[DBUG] Content/Output » Skipping pipeline due to dependency error
[DBUG] AnalyzeContent/Input » Skipping pipeline due to dependency error
[DBUG] AnalyzeContent/Process » Skipping pipeline due to dependency error
[DBUG] AnalyzeContent/PostProcess » Skipping pipeline due to dependency error
[DBUG] AnalyzeContent/Output » Skipping pipeline due to dependency error
[INFO] ========== Execution Summary =========`
```

```
PS E:\Experiments\StatiqWebQuickStartWithCleanBlogTheme\StatiqWebQuickStartWithCleanBlogTheme> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.203
 Commit:    383637d63f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.203\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  3.1.409 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
PS E:\Experiments\StatiqWebQuickStartWithCleanBlogTheme\StatiqWebQuickStartWithCleanBlogTheme>
```

**Comment by daveaglick** [comment]
Running Statiq.Web.Examples appears to exhibit the problem as a repro, so that project should be added to the unit test suite as an integration test to prevent similar regressions in the future.

**Comment by daveaglick** [comment]
This is resolved _for real_ (I think). The remaining issues had to do more with something working that shouldn't have when it came to the model type of layouts and partials. That's been "fixed" but might cause some regressions if the site is currently using `@Model` to access the current document in layouts or partials.

See the [release notes](https://github.com/statiqdev/Statiq.Framework/releases/tag/v1.0.0-beta.44) for more detail.

**Comment by henrikrxn** [comment]
Given the simplicity of reproducing I didn't respond to either fix.

But both work for me.

**Comment by daveaglick** [comment]
Great, thanks for the confirmation @henrikrxn!
